# Generated by Django 6.1.1 on 2026-09-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_householdmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='chores.household')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'name'), name='unique_category_per_household')],
            },
        ),
    ]
