# Generated by Django 6.1.1 on 2026-09-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CHORE', 'Chore'), ('ONE_OFF', 'One-off')], max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('estimated_effort', models.PositiveIntegerField(blank=True, null=True)),
                ('workload_points', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='chores.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chores.household')),
            ],
        ),
    ]
