# Generated by Django 6.1.1 on 2026-09-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_mode',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('JOINT', 'Joint'), ('ANY_OF', 'Any of')], default='SINGLE', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_task_assignment')],
            },
        ),
    ]
