# Generated by Django 6.1.1 on 2026-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_task_assignment_mode_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rotation_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
