# Generated by Django 6.1.1 on 2026-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_task_rotation_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_mode',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('JOINT', 'Joint'), ('ANY_OF', 'Any of'), ('CLAIMABLE', 'Claimable pool')], default='SINGLE', max_length=10),
        ),
    ]
