# Generated by Django 6.1.1 on 2026-09-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_alter_task_assignment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('INTERVAL', 'Every N days'), ('WEEKDAYS', 'Weekdays'), ('MONTHLY_WEEKDAY', 'First weekday of month')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='chores.task')),
            ],
        ),
    ]
