# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_recurrencerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'scheduled_date'), name='unique_task_occurrence')],
            },
        ),
    ]
