# Generated by Django 6.1.1 on 2026-09-07 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.taskoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'user'), name='unique_occurrence_completion')],
            },
        ),
    ]
