# Generated by Django 6.1.1 on 2026-09-07 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0013_approval_completionproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_due', models.BooleanField(default=True)),
                ('overdue', models.BooleanField(default=True)),
                ('assignments', models.BooleanField(default=True)),
                ('rotation_changes', models.BooleanField(default=True)),
                ('completions', models.BooleanField(default=True)),
                ('approval_requests', models.BooleanField(default=True)),
                ('approval_results', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
