# Generated by Django 6.1.1 on 2026-09-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0016_household_gamification_enabled_pointsledger_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
