# Generated by Django 6.1.1 on 2026-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0017_recurrencerule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='require_proof_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='require_proof_photo',
            field=models.BooleanField(default=False),
        ),
    ]
