# Generated by Django 6.1.1 on 2026-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0018_task_require_approval_task_require_proof_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
